export {
  resolvePackageRoot,
  defaultBinDir,
  defaultInstallHome,
  lifecycleScriptName,
  lifecycleProcessArgs,
  updateAssentor,
  uninstallAssentor,
  runScript,
  resolveAssentorBinary,
  buildAssentorLaunchCommand,
  relaunchAssentor,
  runAssentorSubcommand,
} from "./lifecycle.js";
export {
  getLocalVersionSync,
  checkForUpdate,
  clearUpdateCheckCache,
  isRemoteNewer,
  isUpdateCacheReusable,
  parseSemver,
  readChangelog,
  updateCheckCachePath,
  ASSENTOR_CHANGELOG_URL,
  ASSENTOR_PACKAGE_URL,
  type UpdateCheckResult,
} from "./version.js";
